const RobotoFontName = "'Roboto', sans-serif";
// const RobotoFontName = "Helvetica Neue, helvetica, sans-serif";

const typography = {
  fontFamily: RobotoFontName,
  fontWeightLight: 300,
  fontWeightRegular: 400,
  fontWeightMedium: 500,
  fontWeightBold: 700,
  heading: {
    fontFamily: RobotoFontName,
    fontSize: "1.4rem",
    fontStyle: "normal",
    lineHeight: "1.5rem",
    fontWeight: 500,
    letterSpacing: "0.0094rem",
  },
  heading_1: {
    fontFamily: RobotoFontName,
    fontSize: "1.4rem",
    fontStyle: "normal",
    lineHeight: "1.75rem",
    fontWeight: 400,
    letterSpacing: "0.0094rem",
  },
  title: {
    fontFamily: RobotoFontName,
    fontSize: "1.15rem",
    fontStyle: "normal",
    lineHeight: "1.5rem",
    fontWeight: 400,
    letterSpacing: "0.0094rem",
  },
  title_1: {
    fontFamily: RobotoFontName,
    fontSize: "1.15rem",
    fontStyle: "normal",
    lineHeight: "1.31rem",
    fontWeight: 500,
    letterSpacing: "0.0094rem",
  },
  body: {
    fontFamily: RobotoFontName,
    fontSize: "0.9rem",
    fontStyle: "normal",
    lineHeight: "1.5rem",
    fontWeight: 400,
    letterSpacing: "0.0094rem",
  },
  body_1: {
    fontFamily: RobotoFontName,
    fontSize: "0.9rem",
    fontStyle: "normal",
    lineHeight: "1.5rem",
    fontWeight: 500,
    letterSpacing: "0.0094rem",
  },
  body_2: {
    fontFamily: RobotoFontName,
    fontSize: "0.9rem",
    fontStyle: "normal",
    lineHeight: "1.25rem",
    fontWeight: 400,
    letterSpacing: "0.0094rem",
  },
  body_3: {
    fontFamily: RobotoFontName,
    fontSize: "0.9rem",
    fontStyle: "normal",
    lineHeight: "1.125rem",
    fontWeight: 400,
    letterSpacing: "0.0094rem",
  },
  body2: {
    fontFamily: RobotoFontName,
    fontSize: "0.775rem",
    fontStyle: "normal",
    lineHeight: "1.625rem",
    fontWeight: 400,
    letterSpacing: "0.0094rem",
  },
  body2_1: {
    fontFamily: RobotoFontName,
    fontSize: "0.775rem",
    fontStyle: "normal",
    lineHeight: "1.625rem",
    fontWeight: 400,
    letterSpacing: "0.0094rem",
  },
  caption: {
    fontFamily: RobotoFontName,
    fontSize: "0.775rem",
    fontStyle: "normal",
    lineHeight: "1.5rem",
    fontWeight: 400,
    letterSpacing: "0.0094rem",
  },
  caption_1: {
    fontFamily: RobotoFontName,
    fontSize: "0.65rem",
    fontStyle: "normal",
    lineHeight: "0.875rem",
    fontWeight: 400,
    letterSpacing: "0.0094rem",
  },
};

export default typography;
