export const END_POINTS = {
  ANALYSIS_GATEWAY: "/analysis-gateway",
  LOGIN: "/api/authenticate",
  ANALYSIS: "/v3/analysis/",
  SHOW_MORE: "/v3/fetch/",
  SAVE_REPOSITORY: "/api/saveToRepository/",
  QR_CODE: "/api/getQr",
  DOWNLOAD_REPORT: "/api/download2/",
  DOWNLOAD_HTML_REPORT: "/api/downloadHtmlReport/",
  DOWNLOAD_SUMMARY: "/api/download/summary/",
  EMAIL_NOTIFICATION: "/api/emailNotification/",
  FILE_INFORMATION: "/api/fileInformation",
  EXCLUDE_SOURCE: "/v3/excludeSource/",
  INCLUDE_SOURCE: "/v3/includeSource/",
  PLAGARISM_SETTING: "/api/plagiarismSettings/",
  FEEDBACK_GRADE: "/api/feedback",
  GET_SIMILARITY: "/v3/getSimilarity/",
  PLAGIARISM_SETTINGS: "/api/plagiarismSettings/",
  DUPLICATE_PHRASES: "/api/getDuplicates/",
  GET_SETTINGS_DETAIL: "/api/getSettings/",
  DOWNLOAD_API_REPORT: "/api/ai/download2",
  SHARE_ANALYSIS_PAGE: "/analysis/email/",
  ANALYSIS_VERSION: "/v3/test2/",
  IMAGE_PATH: "/api/images/",
  AI_VERSION: "/v3/ai/",
};
