import { Button, Grid, Box, Typography } from "@mui/material";
import styled from "styled-components";

const FooterContainer = styled(Box)`
  padding: 0rem;
  margin: 3rem 0rem;
  text-align: center;
`;

const SignatureTitle = styled.div`
  font-size: 1rem;
  font-weight: 500;
  margin-bottom: 3rem;
`;

const printArticle = () => {
  window.print();
};

const DigitalReceiptFooter = ({ titles }) => {
  return (
    <FooterContainer>
      <Grid container spacing={2} justifyContent="space-between">
        {titles.map((title, index) => (
          <Grid item key={index}>
            <SignatureTitle>{title}</SignatureTitle>
          </Grid>
        ))}
      </Grid>
      <Typography variant="caption_1" sx={{ color: "red" }}>
        * This report has been generated by DrillBit Anti-Plagiarism Software
      </Typography>
      <Button
        id="hidden-print"
        variant="contained"
        color="primary"
        onClick={printArticle}
        sx={{ width: "60%" }}
      >
        Print
      </Button>
    </FooterContainer>
  );
};

export default DigitalReceiptFooter;
